spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: public
  datasource:
    url: jdbc:postgresql://${APP_DATABASE_ADDR}/${APP_DATABASE}
    username: ${APP_DATABASE_USERNAME}
    password: ${APP_DATABASE_PASSWORD}
server:
  port: 8081
